export { default as About } from './About';
export { default as Home } from './Home';
export { default as Recent } from './Recent';
export { default as Search } from './Search';
export { default as SignIn } from './SignIn';
export { default as SinglePost } from './SinglePost';
export { default as Splash } from './Splash';
export { default as Terms } from './Terms';
export { default as User } from './User';
